grails-app/controllers/relatorios/RelatorioFechamentoController.groovy
package relatorios

import grails.converters.JSON
import groovy.sql.Sql

import java.text.SimpleDateFormat

import net.sf.jasperreports.engine.JRExporter
import net.sf.jasperreports.engine.JasperPrint
import net.sf.jasperreports.engine.export.JRXlsExporterParameter

import org.apache.commons.codec.binary.Base64
import org.codehaus.groovy.grails.plugins.jasper.JasperExportFormat
import org.codehaus.groovy.grails.plugins.jasper.JasperReportDef
import org.hibernate.SessionFactory
import org.springframework.context.ApplicationContext
import org.springframework.transaction.annotation.Transactional

import acesso.Usuario
import cadastros.Ocorrencias
import cadastros.ParamRelatorioFechamento
import cadastros.ParamRelatorioFechamentoOcorrencia;
import cadastros.ParamRelatorioHorasExtras
import cadastros.ParamRelatorioHorasExtrasOcorrencia
import cadastros.Periodo


@Transactional
class RelatorioFechamentoController {

    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]
	
	def filtroPadraoService
	def detectDataBaseService
	def relatoriosService
	def jasperService
	def dataSource
	SessionFactory sessionFactory
	
	def index() {
		Usuario usuario = session['usuario']
		def filtros = ParamRelatorioFechamento.findAllByUsuario(usuario)
		
		[filtros: filtros]
	}
	
	def generateReport() {
		
		String query = generateSql(params)
		println "### Consulta do relatorio: " + query
		Sql sql = new Sql(dataSource)
		def results = []
		
		try {
			results = sql.rows(query)
		} catch(Exception e) {
			e.printStackTrace()
			flash.message = "Sem registros"
			redirect(action: "index")
		}
		
		if (results.isEmpty()) {
			render(status: response.SC_BAD_REQUEST)
		}
		
		
		def format = params._format.equals("PDF") ? JasperExportFormat.PDF_FORMAT : JasperExportFormat.XLS_FORMAT
		def contentType = format.mimeTyp
		def fileName = 'report.'.concat(format.extension)
		def reportName = generateReportName()
		def parameters = generateParameters()
		
		JasperReportDef reportDef = new JasperReportDef(
			name: reportName,
			fileFormat: format,
			reportData: results,
			parameters: parameters
		)

		ByteArrayOutputStream saida = new ByteArrayOutputStream();		
		
		JasperPrint printer = jasperService.generatePrinter(reportDef);
		JRExporter exp = jasperService.generateExporter(reportDef);
		
		exp.setParameter(JRXlsExporterParameter.JASPER_PRINT, printer);
		exp.setParameter(JRXlsExporterParameter.IGNORE_PAGE_MARGINS, false);
		exp.setParameter(JRXlsExporterParameter.IS_COLLAPSE_ROW_SPAN, true);
		exp.setParameter(JRXlsExporterParameter.IS_WHITE_PAGE_BACKGROUND, false);
		exp.setParameter(JRXlsExporterParameter.IS_REMOVE_EMPTY_SPACE_BETWEEN_COLUMNS, true);
		exp.setParameter(JRXlsExporterParameter.IS_REMOVE_EMPTY_SPACE_BETWEEN_ROWS, true);
		exp.setParameter(JRXlsExporterParameter.IS_DETECT_CELL_TYPE, true);
		exp.setParameter(JRXlsExporterParameter.OUTPUT_STREAM, saida);
		exp.exportReport();
		
		def binaryBase64 = new String(Base64.encodeBase64(saida.toByteArray()))
		def reportData = [reportData: binaryBase64, format: params._format]
		
		session.setAttribute("reportData", binaryBase64)
		session.setAttribute("reportFormat", params._format)
		
		render reportData as JSON
	}
	
	def generateSql(params) {
		
		SimpleDateFormat formatBD = null
		if (detectDataBaseService.isPostgreSql()) {
			formatBD = new SimpleDateFormat("yyyy-MM-dd")
		} else {
			formatBD = new SimpleDateFormat("dd/MM/yyyy")
		}
		
		def periodo = Periodo.get(params.periodo)
		def dtInicio = new SimpleDateFormat("dd/MM/yyyy").format(periodo.dtIniPr)
		def dtFim = new SimpleDateFormat("dd/MM/yyyy").format(periodo.dtFimPr)
		
		def dtInicioParam = formatBD.format(periodo.dtIniPr)
		def dtFimParam = formatBD.format(periodo.dtFimPr)
		
		def sql = ""
		
		def tipoRelatorio = params.tipoRelatorio
		def agrupamento = params.agrupamento
		def format = params._format
		
		if (params.relatorio.equals("0")) {
			sql = format.equals("PDF") ? 
				generateSqlFechamentoDoMesPDF(tipoRelatorio, agrupamento, periodo.id) : 
				generateSqlFechamentoDoMesExcel(tipoRelatorio, agrupamento, periodo.id)
		} else if (params.relatorio.equals("1")) {
			sql = format.equals("PDF") ?
				generateSqlFechamentoMensalPDF(tipoRelatorio, agrupamento, periodo.id) :
				generateSqlFechamentoMensalExcel(tipoRelatorio, agrupamento, periodo.id)
		}
		
		sql 
	}
	
	def generateSqlFechamentoDoMesPDF(tipoRelatorio, agrupamento, periodoId) {
		def selectClause = " select "
		def groupByClause = " group by "
		
		if (tipoRelatorio.equals("0")) {
			if (detectDataBaseService.isPostgreSql()) {
				selectClause = selectClause + " distinct f.mtr_func::int8 as seq, f.nom_func as descricao  "
			} else {
				selectClause = selectClause + " distinct cast(f.mtr_func as integer) as seq, f.nom_func as descricao  "
			}
			
			groupByClause = " "
		} else {
			switch (agrupamento) {
				case "0":
					selectClause =  selectClause + " distinct fil.id as seq, fil.dsc_fil as descricao "
					groupByClause = groupByClause + " fil.id, fil.dsc_fil "
					break
				case "1":
					selectClause =  selectClause + " distinct s.id as seq, s.dsc_setor as descricao "
					groupByClause = groupByClause + " s.id, s.dsc_setor "
					break
				case "2":
					selectClause =  selectClause + " distinct c.id as seq, c.dsc_cargo as descricao "
					groupByClause = groupByClause + " c.id, c.dsc_cargo "
					break
				case "3":
					selectClause =  selectClause + " distinct f.crc_func as seq, f.nom_func as descricao "
					groupByClause = groupByClause + " f.crc_func, f.nom_func "
					break
			}
		}
		
		
		def sql = selectClause
		sql = sql + " from fechamento fec "
		sql = sql + " join periodo p on fec.seq_pr = p.id "
		sql = sql + " join funcionario f on fec.seq_func = f.id "
		sql = sql + " join filial fil on f.filial_id = fil.id "
		sql = sql + " join cargo c on f.cargo_id = c.id "
		sql = sql + " join setor s on f.setor_id = s.id "
		sql = sql + " join ocorrencias o on fec.seq_ocor = o.id "
		
		sql = sql + " where p.id = ${periodoId} "
		sql = sql + filtroPadraoService.montaFiltroPadraoSqlNativo(params)
		sql = sql + " and o.id in ( " + params.ocorrenciasId.toString().replace('[', ' ').replace(']', ' ') + " ) "
		
		sql = sql + groupByClause
		
		sql = sql + " order by " + (params.ordenacao.toInteger() == 1 ? " seq " : " descricao ")
		
		sql
	}
	
	def generateSqlFechamentoDoMesExcel(tipoRelatorio, agrupamento, periodoId) {
		def selectClause = " select "
		def groupByClause = " group by "
		
		if (tipoRelatorio.equals("0")) {
			selectClause = selectClause + " f.id as seq, f.mtr_func as matricula, f.crc_func as cracha, f.nom_func as nome,  "
			selectClause = selectClause + " s.dsc_setor as setor, o.dsc_ocor as ocorrencia, fec.nr_qt_horas as quant_horas, fec.nr_qt as quant_dias "
			groupByClause = " "
		} else {
			switch (agrupamento) {
				case "0":
					selectClause =  selectClause + " fil.id as seq, fil.dsc_fil as descricao, o.dsc_ocor as ocorrencia,  "
					selectClause =  selectClause + " sum(fec.nr_qt_horas) as quant_horas, sum(fec.nr_qt) as quant_dias "
					groupByClause = groupByClause + " fil.id, fil.dsc_fil, o.dsc_ocor "
					break
				case "1":
					selectClause =  selectClause + " s.id as seq,s.dsc_setor as descricao, o.dsc_ocor as ocorrencia,  "
					selectClause =  selectClause + " sum(fec.nr_qt_horas) as quant_horas, sum(fec.nr_qt) as quant_dias "
					groupByClause = groupByClause + " s.id, s.dsc_setor, o.dsc_ocor "
					break
				case "2":
					selectClause =  selectClause + " c.id as seq , c.dsc_cargo as descricao, o.dsc_ocor as ocorrencia,  "
					selectClause =  selectClause + " sum(fec.nr_qt_horas) as quant_horas, sum(fec.nr_qt) as quant_dias "
					groupByClause = groupByClause + " c.id , c.dsc_cargo, o.dsc_ocor "
					break
				case "3":
					selectClause =  selectClause + " f.crc_func as seq, f.nom_func as descricao, o.dsc_ocor as ocorrencia, "
					selectClause =  selectClause + " sum(fec.nr_qt_horas) as quant_horas, sum(fec.nr_qt) as quant_dias "
					groupByClause = groupByClause + " f.crc_func, f.nom_func, o.dsc_ocor "
					break
			}
		}
		
		
		def sql = selectClause
		sql = sql + " from fechamento fec "
		sql = sql + " join periodo p on fec.seq_pr = p.id "
		sql = sql + " join funcionario f on fec.seq_func = f.id "
		sql = sql + " join filial fil on f.filial_id = fil.id "
		sql = sql + " join cargo c on f.cargo_id = c.id "
		sql = sql + " join setor s on f.setor_id = s.id "
		sql = sql + " join ocorrencias o on fec.seq_ocor = o.id "
		
		sql = sql + " where p.id = ${periodoId} "
		sql = sql + filtroPadraoService.montaFiltroPadraoSqlNativo(params)
		sql = sql + " and o.id in ( " + params.ocorrenciasId.toString().replace('[', ' ').replace(']', ' ') + " ) "
		
		sql = sql + groupByClause
		
		if (tipoRelatorio.equals("0") || params.relatorio.equals("3")) {
			def paramOrdenacao = (params.ordenacao.toInteger() == 1 ? " seq " : " nome ")
			sql = sql + " order by " + paramOrdenacao + ", ocorrencia "
		} else {
			def paramOrdenacao = (params.ordenacao.toInteger() == 1 ? " seq " : " descricao ")
			sql = sql + " order by " + paramOrdenacao + ", ocorrencia "
		}
		
		sql
	}
	
	def generateSqlFechamentoMensalPDF(tipoRelatorio, agrupamento, periodoId) {
		def selectClause = " select "
		def groupByClause = " group by "
		
		if (tipoRelatorio.equals("0")) {
			if (detectDataBaseService.isPostgreSql()) {
				selectClause = selectClause + " distinct f.mtr_func::int8 as seq, f.nom_func as descricao  "
			} else {
				selectClause = selectClause + " distinct cast(f.mtr_func as integer) as seq, f.nom_func as descricao  "
			}
			
			groupByClause = " "
		} else {
			switch (agrupamento) {
				case "0":
					selectClause =  selectClause + " distinct fil.id as seq, fil.dsc_fil as descricao "
					groupByClause = groupByClause + " fil.id, fil.dsc_fil "
					break
				case "1":
					selectClause =  selectClause + " distinct s.id as seq, s.dsc_setor as descricao "

grails-app/views/relatorioFechamento/index.gsp
<%@page import="cadastros.Periodo"%>
<%@page import="cadastros.Ocorrencias"%>
<html>
  <head>
    <meta name="layout" content="main">
  </head>

  <body>
  
  	<g:javascript src="jquery.meiomask.js"/>
    <g:javascript src="comum/lov.js"/>
    <g:javascript src="reports/reports.js"/>
    <g:javascript src="reports/fechamento.js"/>
    
    <g:if test="${flash.message}">
    <div class="alert alert-info" role="status">${flash.message}</div>
    </g:if>

    <g:if test="${flash.error}">
    <div class="alert alert-error" role="status">${flash.error}</div>
    </g:if>

    <div class="titulo">
      <h3>Relatório de fechamento</h3>
    </div>
    
    <g:jasperForm controller="relatorioFechamento" action="generateReport" jasper="fechamento" class="form-horizontal" id="formPesquisa">
    
    	<div class="well">
    	
    		<div class="well" style="border: 1px solid #859CA4; background-color: #859CA4;">
				<div class="control-group">
					<label class="control-label" style="font-weight: bold;">Filtro:</label>
					<div class="controls">
						<input type="hidden" name="filtroId" id="filtroId">
						<input type="hidden" name="filtroPadrao_FilialId" id="filtroPadrao_FilialId" value="${params.filtroPadrao_FilialId}">
						<input type="hidden" name="filtroPadrao_CargoId" id="filtroPadrao_CargoId" value="${params.filtroPadrao_CargoId}">
						<input type="hidden" name="filtroPadrao_DepartamentoId" id="filtroPadrao_DepartamentoId" value="${params.filtroPadrao_DepartamentoId}">
						<input type="hidden" name="filtroPadrao_FuncionarioId" id="filtroPadrao_FuncionarioId" value="${params.filtroPadrao_FuncionarioId}">
						<input type="hidden" name="filtroPadrao_TipoFuncionarioId" id="filtroPadrao_TipoFuncionarioId" value="${params.filtroPadrao_TipoFuncionarioId}">
						<input type="hidden" name="filtroPadrao_HorarioId" id="filtroPadrao_HorarioId" value="${params.filtroPadrao_HorarioId}">
						<input type="hidden" name="filtroPadrao_SubUniOrgId" id="filtroPadrao_SubUniOrgId" value="${params.filtroPadrao_SubUniOrgId}">
						<input type="hidden" name="filtroPadrao_NaoListaDemitidos" id="filtroPadrao_NaoListaDemitidos" value="${params.filtroPadrao_NaoListaDemitidos}">
						
						<g:textField name="filtroDesc" readonly="true" style="width:300px" value="${params.filtroDesc}"/>
						<i class="icon-search" style="cursor: pointer" id="filtroBusca" onclick="showFiltroPadrao();"></i>&nbsp;
					</div>
				</div>
			</div>
			
			<div class="tabbable"> 
			    <ul class="nav nav-tabs">
				    <li class="active"><a href="#tab1" data-toggle="tab">Opções básicas</a></li>
				    <li><a href="#tab2" data-toggle="tab">Seleção das Ocorrências</a></li>
			    </ul>
			    <div class="tab-content">
			    
			    	<!--
			    	  --
			    	  -- TAB OPCOES BASICAS
			    	  -- 
			    	 -->
				    <div class="tab-pane active" id="tab1">
				    	
				    	<g:if test="${filtros != null && filtros.size() > 0}">
					    	<div class="control-group">
								<label class="control-label" style="font-weight: bold;">Filtro:</label>
								<div class="controls">
									<g:select id="filtroSalvo" name="filtroSalvo" noSelection="['':'..']"
										from="${filtros}" optionKey="id" required="" onchange="aplicaFiltro();"/>
								</div>
							</div>
						</g:if>
				    
				    	<div class="control-group">
							<label class="control-label" style="font-weight: bold;">Ano:</label>
							<div class="controls">
								<g:select id="ano" name="ano" onchange="mudaAno()" style="width:145px;" noSelection="['':'..']"
									from="${Periodo.executeQuery('select distinct year(p.dtIniPr) as ano from Periodo p order by 1 asc')}" />
							</div>
						</div>
				    
				    	<div class="control-group">
							<label class="control-label" style="font-weight: bold;">Período:</label>
							<div class="controls">
								<select id="periodo" name="periodo" onchange="mudaPeriodo()" style="width: 145px;">
									<option value="">..</option>
								</select>
								
							</div>
						</div>
						
						<div class="control-group">
							<label class="control-label" style="font-weight: bold;">Data início:</label>
							<div class="controls">
								<g:textField name="dataInicio" value="${params.dataInicio}" style="width:80px" readonly="readonly"/>
							</div>
						</div>
						
						<div class="control-group">
							<label class="control-label" style="font-weight: bold;">Data fim:</label>
							<div class="controls">
								<g:textField name="dataFim" value="${params.dataFim}" style="width:80px" readonly="readonly"/>
							</div>
						</div>
						
						<div class="control-group">
							<label class="control-label" style="font-weight: bold;">Relatório:</label>
							<div class="controls">
								<g:select name="relatorio" id="relatorio" optionKey="id" optionValue="nome" 
										value="${params.relatorio}"
										style="width:200px;"
										from="${[ [id:'0', nome:'Fechamento do mês'],
												  [id:'1', nome:'Fechamento Mensais']  ]}"/>
							</div>
						</div>
						
						<div class="control-group">
							<label class="control-label" style="font-weight: bold;">Tipo de relatório:</label>
							<div class="controls">
								<g:select name="tipoRelatorio" id="tipoRelatorio" optionKey="id" optionValue="nome" 
										value="${params.tipoRelatorio}"
										style="width:100px;"
										from="${[ [id:'0', nome:'Analítico'],
												  [id:'1', nome:'Sintético']  ]}"/>
							</div>
						</div>
						
						<div class="control-group">
							<label class="control-label" style="font-weight: bold;">Tipo de agrupamento:</label>
							<div class="controls">
								<g:select name="agrupamento" id="agrupamento" optionKey="id" optionValue="nome" 
										value="${params.agrupamento}"
										style="width:150px;"
										from="${[ [id:'0', nome:'Filial'],
												  [id:'1', nome:'Departamento'],
												  [id:'2', nome:'Função'],
												  [id:'3', nome:'Funcionário']  ]}"/>
							</div>
						</div>
						
						<div class="control-group">
							<label class="control-label" style="font-weight: bold;">Ordenação:</label>
							<div class="controls">
								<g:select name="ordenacao" id="ordenacao" optionKey="id" optionValue="nome" 
										value="${params.ordenacao}"
										style="width:200px;"
										from="${[ [id:'1', nome:'Código'],
												  [id:'2', nome:'Descrição'] ]}"/>
							</div>
						</div>
						
				    </div>
				    
				    <!--
			    	  --
			    	  -- TAB SELECOES OCORRENCIAS
			    	  -- 
			    	 -->
				    <div class="tab-pane" id="tab2">
				    	
				    	<table class="table table-striped table-bordered table-condensed" id="ocorrenciasTable">
				    		<thead>
				    			<tr>
				    				<th>Seq</th>
				    				<th>Ocorrência</th>
				    				<th>&nbsp;</th>
				    			</tr>
				    		</thead>
				    		<tbody id="tbodyOcor">
					    		<g:each in="${Ocorrencias.findAll('from Ocorrencias o ')}" var="ocorrencia">
					    			<tr id="rowTableOcorrencia${ocorrencia.id}">
					    				<td>
					    					${ocorrencia.id}
					    					<input type="hidden" name="ocorrenciasId" id="ocorrenciasId" value="${ocorrencia.id}">
					    				</td>
					    				<td>${ocorrencia.dscOcor}</td>
					    				<td>
					    					<i class="icon-remove" onclick="excluirOcorrencia(${ocorrencia.id});" style="cursor: pointer" title="Excluir registro"></i>
					    				</td>
					    			</tr>
					    		</g:each>
				    		</tbody>
				    	</table>
				    	<input type="hidden" name="ocorrenciasId" id="ocorrenciasId" value="0">
				    </div>
				    
				</div>
				
			</div>
			
			<input type="hidden" id="urlSalvarFiltro" name="urlSalvarFiltro" value="/relatorioFechamento/salvarFiltro">
				    
			<button class="btn btn-medium btn-primary" onclick="if (validateReport()) generateReport('PDF'); else return false;">Gerar em PDF</button>
			<button class="btn btn-medium btn-primary" onclick="if (validateReport()) generateReport('XLS'); else return false;">Gerar em Excel</button>
			<button class="btn btn-medium btn-primary" onclick="showSalvarFiltro();" type="button">Salvar filtro</button>
    	
		</div>
    
    </g:jasperForm>
    
    <g:render template="/busca/lovPadrao"/>
    <g:render template="/busca/lovBuscaInterna"/>
    <g:render template="/relatorio/modalSalvarFiltro"/>

    <div id="carregando" class="carregandoDiv">
	    <div id="carregandoDiv" style="position:absolute; left:50%; top:50%; margin-left: -110px;">
	    	<img src="${resource(dir:'images',file:'ajax-loader.gif')}" class="ph"/>
	    </div>
    </div>
    
  </body>
</html>